id: Cyberpion Domain State
inputs: []
name: Cyberpion Domain State
outputs: []
description: Allows analyst to get basic information about the domain
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: abe22634-6ede-4f30-839c-23e8b2fff5c0
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: abe22634-6ede-4f30-839c-23e8b2fff5c0
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    id: "1"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 36cd4c75-7523-46fe-8fa2-6830aa8bae9a
      description: Allows analyst to get basic information about the domain
      iscommand: false
      name: DeleteContext
      script: DeleteContext
      type: regular
      version: -1
    taskid: 36cd4c75-7523-46fe-8fa2-6830aa8bae9a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "2":
    evidencedata:
      customfields: {}
      description:
        simple: This result is an evidence
    id: "2"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      domain:
        simple: ${incident.cyberpiondomain}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Cyberpion
      description: Retrieves domain's info and current state
      id: a7b8aa7b-dd11-454a-8eca-67b80db4a909
      iscommand: true
      name: cyberpion-get-domain-state
      script: Cyberpion|||cyberpion-get-domain-state
      type: regular
      version: -1
    taskid: a7b8aa7b-dd11-454a-8eca-67b80db4a909
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "4":
    id: "4"
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: c66d7ef7-ec0d-448b-8264-81ed929b37bb
      iscommand: false
      name: Done
      type: title
      version: -1
      description: ''
    taskid: c66d7ef7-ec0d-448b-8264-81ed929b37bb
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
  "6":
    id: "6"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Steps:
        #Review evidence
      id: 814800e5-7cb7-453e-8d01-c074c6083f47
      iscommand: false
      name: Wait for manual review
      type: regular
      version: -1
    taskid: 814800e5-7cb7-453e-8d01-c074c6083f47
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "7":
    id: "7"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      assetid: {}
      closeNotes: {}
      closeReason: {}
      emailclassification: {}
      id: {}
      incomingmirrorerror: {}
      outgoingmirrorerror: {}
      phishingsubtype: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: 8e4e42b5-2bd5-43ca-82af-f976017cb3e6
      iscommand: true
      name: Close investigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 8e4e42b5-2bd5-43ca-82af-f976017cb3e6
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 910,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
tests:
- Cyberpion-Test
fromversion: 6.0.0
